### ISSUE TITLE
No solver available, examples will not work

### ISSUE THREAD

**Issue by AllenShi666** [coin-or/Osi#139]
I was using mingw64 on windows to compile Bonmin and eveything was done using coinbrew, then the only error I had is from Osi 0.108.6, the output looks like this: <code>configure: WARNING: No solver available, examples will not work</code>. I was trying to figure out what the reason behind this.

**Comment by tkralphs** [comment]
This is because when Osi was built, it did not know about any available LP solvers (Clp is built afterwards, since Osi is a dependency of Clp). If you want any of the examples that ship with Osi to work right after building Osi, it would need to have a solver available to it at confirgure time so it can generate the Makefiles with the proper paths, etc. This is not a big deal, especially if you are just using it as part of Bonmin. If you did want to the examples and their Makefile to work out of the box with Clp, you could go back and re-configure Osi after installing Clp.

**Comment by LouHafer** [comment]
Or build and install glpk. Closing this issue.
